-- ============================================================
-- MEDICAL CHATBOT - COMPLETE DATABASE SETUP
-- Thesis: Design and Implementation of a Task-Oriented 
--         Medical Chatbot using Llama 3 8B
-- Author: Baiyifan
-- Date: 2026
-- ============================================================

-- ============================================================
-- PART 1: CREATE DATABASE
-- ============================================================

-- Drop database if exists (CAUTION: This deletes all data)
-- Uncomment if you want to start fresh
-- DROP DATABASE IF EXISTS medical_chatbot;

-- Create new database with UTF-8 support for multilingual content
CREATE DATABASE IF NOT EXISTS medical_chatbot 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

-- Select the database for use
USE medical_chatbot;

-- ============================================================
-- PART 2: CREATE TABLES
-- ============================================================

-- ------------------------------------------------------------
-- Table 1: conversations
-- Stores all conversation history between users and the chatbot
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conversations (
    -- Primary key: unique identifier for each conversation turn
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Unique record identifier',
    
    -- Session identifier: groups messages from the same user session
    session_id VARCHAR(64) NOT NULL COMMENT 'Unique session identifier for grouping conversations',
    
    -- User input: the message sent by the user
    user_message TEXT NOT NULL COMMENT 'User input message content',
    
    -- Bot response: the reply generated by the Llama 3 8B model
    bot_response TEXT NOT NULL COMMENT 'Chatbot response generated by Llama 3 8B',
    
    -- Intent detection: identified user intent (symptom, medication, emergency, etc.)
    intent_detected VARCHAR(32) DEFAULT 'general' COMMENT 'Detected user intent from NLP analysis',
    
    -- Performance metric: time taken to generate response in milliseconds
    response_time_ms INT DEFAULT 0 COMMENT 'Response generation time in milliseconds',
    
    -- Timestamp: when the conversation occurred
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    
    -- Indexes for faster query performance
    INDEX idx_session_id (session_id) COMMENT 'Index for session-based queries',
    INDEX idx_created_at (created_at) COMMENT 'Index for time-based queries',
    INDEX idx_intent (intent_detected) COMMENT 'Index for intent-based filtering'
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores all conversation history between users and chatbot';

-- ------------------------------------------------------------
-- Table 2: sessions
-- Tracks user sessions and metadata
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
    -- Primary key
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Unique session record identifier',
    
    -- Session identifier: unique per user session
    session_id VARCHAR(64) NOT NULL UNIQUE COMMENT 'Unique session identifier for tracking',
    
    -- User IP address for analytics and security
    user_ip VARCHAR(45) COMMENT 'User IP address (supports IPv4 and IPv6)',
    
    -- User agent string for browser/device analytics
    user_agent VARCHAR(512) COMMENT 'User browser or device information',
    
    -- Session statistics
    message_count INT DEFAULT 0 COMMENT 'Total number of messages in this session',
    
    -- Timestamps
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Session creation timestamp',
    last_active DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last activity timestamp',
    
    -- Indexes
    INDEX idx_session_id (session_id) COMMENT 'Index for session lookup',
    INDEX idx_last_active (last_active) COMMENT 'Index for session cleanup'
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Tracks user sessions and metadata for analytics';

-- ------------------------------------------------------------
-- Table 3: feedback
-- Stores user feedback for quality improvement (optional)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feedback (
    -- Primary key
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Unique feedback identifier',
    
    -- Foreign key linking to conversation
    conversation_id INT COMMENT 'Reference to the conversation being rated',
    
    -- Session identifier
    session_id VARCHAR(64) COMMENT 'Session identifier for grouping',
    
    -- User rating
    rating TINYINT COMMENT 'User rating from 1 to 5 stars',
    
    -- Detailed feedback text
    feedback_text TEXT COMMENT 'User feedback comments',
    
    -- Binary flag for helpfulness
    is_helpful BOOLEAN DEFAULT NULL COMMENT 'Whether the user found the response helpful',
    
    -- Timestamp
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Feedback submission timestamp',
    
    -- Indexes
    INDEX idx_conversation_id (conversation_id) COMMENT 'Index for conversation-based queries',
    INDEX idx_session_id (session_id) COMMENT 'Index for session-based queries',
    
    -- Foreign key constraint: when a conversation is deleted, keep the feedback but nullify the reference
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE SET NULL
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores user feedback for chatbot quality improvement';

-- ============================================================
-- PART 3: CREATE DATABASE USER
-- ============================================================

-- Create a dedicated user for the Python Flask application
-- Note: Change the password to a secure one in production
CREATE USER IF NOT EXISTS 'chatbot_user'@'localhost' 
IDENTIFIED BY 'MedicalChatbot2024!';

-- Grant all privileges on the medical_chatbot database to this user
GRANT ALL PRIVILEGES ON medical_chatbot.* 
TO 'chatbot_user'@'localhost';

-- Apply the privilege changes
FLUSH PRIVILEGES;

-- ============================================================
-- PART 4: VERIFY DATABASE SETUP
-- ============================================================

-- Show all tables in the database
SELECT '=== TABLES CREATED ===' AS Status;
SHOW TABLES;

-- Show structure of conversations table
SELECT '=== CONVERSATIONS TABLE STRUCTURE ===' AS Status;
DESCRIBE conversations;

-- Show structure of sessions table
SELECT '=== SESSIONS TABLE STRUCTURE ===' AS Status;
DESCRIBE sessions;

-- Show structure of feedback table
SELECT '=== FEEDBACK TABLE STRUCTURE ===' AS Status;
DESCRIBE feedback;

-- ============================================================
-- PART 5: INSERT TEST DATA (OPTIONAL)
-- ============================================================

-- Insert a test session
INSERT INTO sessions (session_id, user_ip, user_agent, message_count) VALUES 
('test-session-001', '127.0.0.1', 'MySQL Workbench / Test Client', 0)
ON DUPLICATE KEY UPDATE message_count = message_count;

-- Insert test conversations
INSERT INTO conversations (session_id, user_message, bot_response, intent_detected, response_time_ms) VALUES 
('test-session-001', 
 'What are the common symptoms of the flu?', 
 'Common flu symptoms include fever (usually over 100°F or 38°C), cough, sore throat, runny or stuffy nose, body aches, headache, chills, and fatigue. Some people may also experience vomiting and diarrhea. If you have difficulty breathing, chest pain, or severe symptoms, please seek immediate medical attention.',
 'symptom', 
 1250),

('test-session-001', 
 'When should I see a doctor for a fever?', 
 'You should see a doctor if: (1) Fever exceeds 103°F (39.4°C), (2) Fever lasts more than 3 days, (3) You have severe headache, rash, difficulty breathing, chest pain, or confusion, (4) You have underlying health conditions. For infants under 3 months, any fever requires immediate medical attention.',
 'general', 
 980),

('test-session-001', 
 'What can I take for headache?', 
 'For mild headaches, you can try: rest in a quiet dark room, stay hydrated, apply a cold or warm compress, and consider over-the-counter pain relievers like acetaminophen or ibuprofen (follow package instructions). If headaches are severe, persistent, or accompanied by other symptoms like vision changes or confusion, please consult a healthcare provider.',
 'medication', 
 1120);

-- Verify test data
SELECT '=== TEST DATA INSERTED ===' AS Status;
SELECT COUNT(*) AS 'Total Conversations' FROM conversations;
SELECT COUNT(*) AS 'Total Sessions' FROM sessions;

-- Show sample data
SELECT '=== SAMPLE CONVERSATION DATA ===' AS Status;
SELECT id, session_id, LEFT(user_message, 50) AS user_msg, LEFT(bot_response, 80) AS bot_response, intent_detected, created_at 
FROM conversations 
ORDER BY created_at DESC 
LIMIT 3;

-- ============================================================
-- PART 6: CREATE ADDITIONAL USEFUL VIEWS (OPTIONAL)
-- ============================================================

-- View 1: Session activity summary
CREATE OR REPLACE VIEW session_activity_summary AS
SELECT 
    s.session_id,
    s.user_ip,
    s.message_count,
    s.created_at AS session_start,
    s.last_active AS last_activity,
    TIMESTAMPDIFF(MINUTE, s.created_at, s.last_active) AS session_duration_minutes,
    COUNT(c.id) AS actual_messages
FROM sessions s
LEFT JOIN conversations c ON s.session_id = c.session_id
GROUP BY s.id
ORDER BY s.last_active DESC;

-- View 2: Daily conversation statistics
CREATE OR REPLACE VIEW daily_stats AS
SELECT 
    DATE(created_at) AS date,
    COUNT(*) AS total_conversations,
    COUNT(DISTINCT session_id) AS unique_sessions,
    AVG(response_time_ms) AS avg_response_time_ms,
    SUM(CASE WHEN intent_detected = 'symptom' THEN 1 ELSE 0 END) AS symptom_queries,
    SUM(CASE WHEN intent_detected = 'medication' THEN 1 ELSE 0 END) AS medication_queries,
    SUM(CASE WHEN intent_detected = 'emergency' THEN 1 ELSE 0 END) AS emergency_queries
FROM conversations
GROUP BY DATE(created_at)
ORDER BY date DESC;

-- ============================================================
-- FINAL STATUS MESSAGE
-- ============================================================
SELECT '=============================================' AS '';
SELECT 'MEDICAL CHATBOT DATABASE SETUP COMPLETE!' AS 'STATUS';
SELECT '=============================================' AS '';
SELECT 'Database: medical_chatbot' AS 'Details';
SELECT 'User: chatbot_user' AS 'Details';
SELECT 'Tables: conversations, sessions, feedback' AS 'Details';
SELECT '=============================================' AS '';

-- Display connection information
SELECT '=== CONNECTION INFORMATION ===' AS '';
SELECT 'Host: localhost' AS 'Connection Details';
SELECT 'Port: 3306' AS 'Connection Details';
SELECT 'Database: medical_chatbot' AS 'Connection Details';
SELECT 'Username: chatbot_user' AS 'Connection Details';
SELECT 'Password: MedicalChatbot2024!' AS 'Connection Details';
SELECT '=============================================' AS '';

USE medical_chatbot;

